### ISSUE TITLE
Certain trigger does not work properly with react-native-zendesk-chat

### ISSUE THREAD

**Issue by beast** [taskrabbit/react-native-zendesk-chat#1]
The image below is a trigger for automated greeting without starting a chat. (I also disable prechat form.) It basically looks for widget being loaded as a condition. My problem is that this trigger does not work with this module and I can't really figure out why.

I opened a case with Zopim and it appears the issue is that the widget is never unloaded when "end chat" is pressed. I tried the same thing on Zopim iOS example app, it works just fine. Which puzzles me because "end chat" is not a button that the module controls. The module simply starts the chat then leave the rest to the lib, same as the iOS example. (https://github.com/zendesk/zendesk_sdk_chat_ios) The framework does all the magic.

I am wondering if anyone knows why that could be an issue. Thanks.

![image](https://cloud.githubusercontent.com/assets/929830/14738715/c422ad70-08b5-11e6-9334-dba749e283c5.png)

**Comment by beast** [comment]
Could you help review the pull request? Thanks.

**Comment by diogoviannaaraujo** [comment]
Having the same problem here, I can set a first reply but not a automated greeting.
Testing on newest version.
