### ISSUE TITLE
Chat messages do not send + android doesnt build

### ISSUE THREAD

**Issue by Giosanu** [taskrabbit/react-native-zendesk-chat#106]
### iOS

I've been trying for a while now to make it work but I cannot.. 
On iOS all I get is this chat.. cannot trigger the form.. or anything else.. the messages do not send and I don't see any activity from the Zendesk chat dashboard

![image](https://user-images.githubusercontent.com/26094928/108359360-932d9c00-71f8-11eb-8aef-564550d7b88d.png)

### Android

on Android it throws this error when trying to build:

``` FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.zendesk:chat:2.2.0.
     Required by:
         project :app > project :react-native-zendesk-chat
   > Could not find com.zendesk:messaging:4.3.1.
     Required by:
         project :app > project :react-native-zendesk-chat
```

I've tried both 0.4.0 and the 0.4.1 beta version but the issues are the same. Anyone else encountered the same issue and managed to find the solution?

### Webview 

I also tried to embed the chat widget in a Webview.. with no luck, it just doesn't render and keeps loading forever..

RN Version: 0.63.3

**Comment by amserhii11** [comment]
@Giosanu Has the same issue. If you find a solution please write it here.

**Comment by fbartho** [comment]
I just verified that it’s working fine for our company as of 10:30am California.

Is it possible this was a transient outage on Zendesk’s side, maybe due to the weather emergency in Texas? Or have you verified that live chat works on your website’s zendesk integration?

**Comment by padupuy** [comment]
@fbartho 

Same problem on iOS in production mode.
The sandbox works well.
No problem on Android ....

```
"react-native": "0.63.4",
"react-native-zendesk-chat": "0.4.1-beta.7"
```

```
ZendeskChat.init(Config.ZENDESK_ACCOUNT_KEY, Config.ZENDESK_APP_ID);
```

```
ZendeskChat.startChat({
      name: `${infos.firstName} ${infos.lastName}`,
      email: infos.email,
      phone: infos.phone,
      tags: [],
      department: brand?.name,
      // The behaviorFlags are optional, and each default to 'true' if omitted
      behaviorFlags: {
        showAgentAvailability: true,
        showChatTranscriptPrompt: true,
        showPreChatForm: false,
        showOfflineForm: true,
      },
      // The preChatFormOptions are optional & each defaults to "optional" if omitted
      preChatFormOptions: {
        name: 'required',
        email: 'hidden',
        phone: 'required',
        department: 'required',
      },
      localizedDismissButtonTitle: strings.close,
    });
```

**Comment by fbartho** [comment]
@padupuy -- that suggests there's something wrong with your account(s) in particular -- this SDK doesn't know anything about the difference between Sandbox and Production.

**Comment by padupuy** [comment]
@fbartho is there a way to enable zendesk log to see a wrong configuration ?

**Comment by fbartho** [comment]
@padupuy I don't know. I would reach out to Zendesk Customer Support (I don't work for Zendesk)

**Comment by padupuy** [comment]
@fbartho FYI To log zendeskChat info 

AppDelegate.m
```
#import <ChatProvidersSDK/ChatProvidersSDK.h>
```
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  #if DEBUG
    ZDKChatLogger.isEnabled = YES;
  #endif
 
    ... 
  
  return YES;
}
```

cf the official sdk documentation : https://developer.zendesk.com/embeddables/docs/chat-sdk-v-2-for-ios/getting_started#logging

It may be useful to enable the logger and the logger level via the `ZendeskChat.init`, what do you thing about this ?

**Comment by Giosanu** [comment]
For whatever reason.. now it is fixed.. but I didn't do anything. 

Except let's say a clean uninstall and reinstall of all the packages
