### ISSUE TITLE
App crashing for ios

### ISSUE THREAD

**Issue by Lokesh235** [taskrabbit/react-native-zendesk-chat#13]
Hi,

I configured SDK of Zendesk Chat for ios according the link: https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/setup

and then as per the instructions given in ReadMe of this Component when I try to start chat, the App is crashing.

Can I get some help or guidance here?

**Comment by agrass** [comment]
Hi @Lokesh235 , you solved the problem?? What version of RN are you using?

**Comment by kirill-kruchkov** [comment]
Kinda necroposting here, but maybe will help someone. I ran into the same issue. The problem was I haven't added `ZDCChat.bundle` and `ZDCChatString.bundle` to `Copy Bundle Resources` section of project in XCode.

**Comment by fbartho** [comment]
Hiya, I know this request was from years ago, so you probably/hopefully got past this issue before now. But if anyone follows, please open a ticket with details so we can help!

We are updating this package this month, if you have any fixes you want to contribute back, please let us know.

Next release milestone: https://github.com/taskrabbit/react-native-zendesk-chat/milestone/1

I’m going to close this ticket, but if it’s still an issue, please let me know!
