### ISSUE TITLE
Build failed on RN 0.70

### ISSUE THREAD

**Issue by 1280103995** [taskrabbit/react-native-zendesk-chat#146]
<img width="347" alt="9a10-fd6d5f4c11c5" src="https://user-images.githubusercontent.com/17424486/201027653-ff3b51ba-1909-453a-9d8c-4bead81ed3f4.png">

**AppDelegate.mm**
```
...
#import <CommonUISDK/CommonUISDK.h>
#import <ChatProvidersSDK/ChatProvidersSDK.h>
...

- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
{
  [ZDKChat registerPushToken:deviceToken];
}
```

**Comment by Ahmed-M-Osman1** [comment]
I have the same issue - can't build nor install without force this package. Any solution ?

**Comment by 1280103995** [comment]
> I have the same issue - can't build nor install without force this package. Any solution ?

Replace header file, it works.
```
#import <CommonUISDK/CommonUISDK-Swift.h>
#import <ChatProvidersSDK/ChatProvidersSDK-Swift.h>
```
