### ISSUE TITLE
Status of repo

### ISSUE THREAD

**Issue by agrass** [taskrabbit/react-native-zendesk-chat#15]
Hi!

Is there someone maintaining this repo?  Works with the last versions of RN? 

The link of the documentation of SDK of IOS is not working anymore. Where I can find that docs? I find this one https://developer.zendesk.com/embeddables/docs/ios/welcome, but is for support SDK.

Thanks!

**Comment by bleonard** [comment]
I updated the links to the current one in the README.
We are currently using this is `0.39.2` - happy to hear of others trying it on newer ones.

**Comment by agrass** [comment]
Great thanks! also in the new version of IOS Chat SDK there are some little changes.
For example this: 
```
[ZDCChat configure:^(ZDCConfig *defaults) {
  defaults.accountKey = "YOUR_ZENDESK_ACCOUNT_KEY";
}];
```
In last version is like this:
```
[ZDCChat initializeWithAccountKey:@"your_account_key"];
```

Thanks for this repo!

**Comment by bleonard** [comment]
hit me with a Pull request!
