### ISSUE TITLE
Bool values in options are not unwrapped

### ISSUE THREAD

**Issue by kirill-kruchkov** [taskrabbit/react-native-zendesk-chat#18]
Hello!

If I pass `visitor.shouldPersist = false` (for `setVisitorInfo`) or `options.emailNotRequired = false` (e.g., for `startChat`) from JS this `options[@"shouldPersist"] || NO` resolves to `YES` when `NO` is expected.

To fix that we should unwrap bool value like that: `[options[@"shouldPersist"] boolValue] || NO`.

Got a PR to submit.

**Comment by fbartho** [comment]
Hiya, I know this request was from years ago, so you probably/hopefully got past this issue before now. But is this still a concern?

We are updating this package this month, if you have any fixes you want to contribute back, please let us know.

Next release milestone: https://github.com/taskrabbit/react-native-zendesk-chat/milestone/1
