### ISSUE TITLE
'RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by pietro909** [taskrabbit/react-native-zendesk-chat#19]
I have this error after the installation of this module:

    project/ios/RNZendeskChatModule.h:3:9: 'RCTBridgeModule.h' file not found

XCode can't build.

**Comment by pietro909** [comment]
I managed to fix it by manually reinstalling Zendesk SDK.

Though now I get

    project/develop/ios/RNZendeskChatModule.m:10:9: fatal error: 'ZDCChat/ZDCChat.h' file not 
    found
    #import <ZDCChat/ZDCChat.h>
            ^
    1 error generated.

My folder structure is:

<img width="251" alt="screen shot 2017-09-21 at 09 26 39" src="https://user-images.githubusercontent.com/2094604/30683815-2e6ffc6a-9eaf-11e7-8420-3b3910a47b2a.png">

**Comment by guillaumecodet** [comment]
@pietro909 did you find a solution for the fatal error: 'ZDCChat/ZDCChat.h' file not 
found ?

**Comment by pietro909** [comment]
we solved it using [Fabric](https://get.fabric.io/)

**Comment by fbartho** [comment]
Hiya, I know this request was from years ago, so you probably/hopefully got past this issue before now. But if anyone follows, please open a ticket with details so we can help!

We are updating this package this month, if you have any fixes you want to contribute back, please let us know.

Next release milestone: https://github.com/taskrabbit/react-native-zendesk-chat/milestone/1

I’m going to close this ticket, but if it’s still an issue, please let me know!
