### ISSUE TITLE
Custom styles

### ISSUE THREAD

**Issue by guillaumecodet** [taskrabbit/react-native-zendesk-chat#20]
Hello, I would like to change the style of the text, and the color of the header, is there a way ?

Thank you.

**Comment by FeMaffezzolli** [comment]
In my case I had a white colored string on a white background. Any solution for this?

![image](https://user-images.githubusercontent.com/26548010/85433036-38a14a80-b55a-11ea-82fc-ceeb6a83161c.png)

**Comment by FeMaffezzolli** [comment]
I figured out and got the result below (android).

Just followed this instructions here: https://developer.zendesk.com/embeddables/docs/android-chat-sdk/customization

For iOS it's pretty much the same logic: https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/customization#styling-your-chat-ui

![image](https://user-images.githubusercontent.com/26548010/85438380-4d81dc00-b562-11ea-9ebe-fb73d21873ff.png)
