### ISSUE TITLE
IOS - ZDCChat/ZDCChat.h not found

### ISSUE THREAD

**Issue by carlocarpio** [taskrabbit/react-native-zendesk-chat#21]
I added ZDCChat via pod install but inside the RNZendeskChatModule.m
it cannot find the ZDCChat/ZDCChat.h. Anyone also have this issue or encountered
this before? thank you very much.

**Comment by guillaumecodet** [comment]
Same issue here :(

**Comment by yasicmd** [comment]
@carlocarpio any solution found?

**Comment by aduycuong** [comment]
Try:
Libraries/RNZendeskChat.xcodeproj > Build Settings > Framework Search Paths
Add: "${SRCROOT}/../../../ios/Pods/ZDCChat" (recursive)

**Comment by limitsapp** [comment]
still having this issue and my Libraries/RNZendeskChat.xcodeproj does not have a Framework Search Paths

**Comment by arcollector** [comment]
have same issue

**Comment by MattyK14** [comment]
My project can has `#import <ZDCChat/ZDCChat.h>` and sees no issues, but this library `RNZendeskChat` cannot see the sdk for some reason. I've added the Framework Search Paths to reference the ZDCChat in `RNZendeskChat` which matches that on my project, but no luck.

**Comment by nyur321** [comment]
@aduycuong Thanks worked for me

**Comment by Frexuz** [comment]
Ye, worked for me too.. Close?

**Comment by Frexuz** [comment]
Do we really have to fork for 1 small change?
I have to add `${SRCROOT}/../../../ios/Pods/ZDCChat` every time I run yarn/rn link

**Comment by Frexuz** [comment]
My fork with the fix if anyone's interested: https://github.com/Frexuz/react-native-zendesk-chat
Created a PR here too :)

**Comment by nyur321** [comment]
@Frexuz waiting for merge

**Comment by mjmaix** [comment]
please merge

**Comment by arcollector** [comment]
you dont need to add `${SRCROOT}/../../../ios/Pods/ZDCChat` to make this library get working

you need to move the files `RNZendeskChatModule.h` and `RNZendeskChatModule.m` into your root project

1. right click onto your project folder, and select the option `"Add files to...."`
2. search the named files at `node_modules/react-native-zendesk-chat/ios` folder
3. done

also you need the zccdchat library
create a `Podile` inside `ios` folder

with this information

```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'WriteHereNameOfYourProject' do
  pod 'ZDCChat'
end
```

save the file, and run the comand: `pod install`

now add
```
$(SRCROOT)/../node_modules/react-native-zendesk-chat/ios
${SRCROOT}/Pods/ZDCChat
```

both as `recursive`, in `Build settings -> Header search paths`

now in your  `AppDelegate.m`, add this line

```
@import ZDCChat;
```

and you are done

**Comment by Frexuz** [comment]
@arcollector but with this PR you don't need those extra steps :)

**Comment by arcollector** [comment]
extra steps? gimme a break, go back to college

**Comment by elirangoshen** [comment]
i still have this issue although i used the library search path

**Comment by Rushi271193** [comment]
Hey I have tried adding the framework paths and yet I get this error. Tried making changes in project.pbxproj of my RNZendesk library yet i get the same error. Any other thing that i need to add? Also tired @import ZDCChat

**Comment by fbartho** [comment]
Hiya, I know this original request was from years ago, so you probably/hopefully got past this issue before now.

We are updating this package this month with updates for cocoapods, and support for react-native 0.60+ if you have any fixes you want to contribute back, please let us know.

Next release milestone: https://github.com/taskrabbit/react-native-zendesk-chat/milestone/1

I’m going to close this ticket for now, and @Rushi271193 (or others) if you’re still struggling with this, let’s file a new github issue to directly investigate your specific case.

As you may know, we aren’t supported by Zendesk, so you may also have to/want to reach out to your representative there at https://developer.zendesk.com
