### ISSUE TITLE
Where do I start chat?

### ISSUE THREAD

**Issue by zorosun** [taskrabbit/react-native-zendesk-chat#22]
Where do I put this code? 

`ZendeskChat.startChat({
  name: user.full_name,
  email: user.email,
  phone: user.mobile_phone,
  tags: ['tag1', 'tag2'],
  department: "Your department"
});
`

in componentDidMount?

**Comment by SMJ93** [comment]
@zorosun You can run it anywhere. We run it when a user clicks `support` in the side menu.

**Comment by fbartho** [comment]
Hiya, I know this request was from years ago, so you probably/hopefully got past this issue before now. @SMJ93 totally answered better than I could.

We are updating this package this month, if you have any fixes you want to contribute back, please let us know.

Next release milestone: https://github.com/taskrabbit/react-native-zendesk-chat/milestone/1

I’m going to close this ticket, but if it’s still an issue, please let me know!
