### ISSUE TITLE
Callback to detect when the Modal is closed

### ISSUE THREAD

**Issue by pietro909** [taskrabbit/react-native-zendesk-chat#23]
Hi there,
when I run

```
ZendeskChat.startChat({ name, email, department })
```

How do I know that the modal was closed?

**Comment by fbartho** [comment]
Honestly? I don’t know the answer to this either. I would reach out to the folks at https://developer.zendesk.com

I know this request was from years ago, so you probably/hopefully got past this issue before now. But if anyone follows, please open a ticket with details so we can help!

We are updating this package this month, if you have any fixes you want to contribute back, please let us know.

Next release milestone: https://github.com/taskrabbit/react-native-zendesk-chat/milestone/1

I’m going to close this ticket, but if it’s still an issue, please let me know!
