### ISSUE TITLE
Styling Android's actionbar

### ISSUE THREAD

**Issue by Frexuz** [taskrabbit/react-native-zendesk-chat#26]
Can't figure out how to get our style reflected in the Actionbar

Our app style has white toolbar background, and black text:
(Blue accent can be black if not possible)
![screen shot 2018-04-24 at 20 37 32](https://user-images.githubusercontent.com/49692/39187290-7bbec060-47ff-11e8-81a9-b7b61e0225af.png)

I've tried ALL POSSIBLE COMBINATIONS inside `chat_style.xml` but all I can get is black toolbar with white text, or white toolbar with white text (invisible text)

```
    <style name="zopim_toolbar">
        <item name="android:background">?attr/colorPrimary</item>
        <item name="android:minHeight">?attr/actionBarSize</item>
       <!-- Tried Light, and Dark here, Theme, ThemeOverlay, Material etc -->
        <item name="android:theme">@style/ThemeOverlay.AppCompat.Dark.ActionBar</item>
       <!-- Tried Light, and Dark here, Theme, ThemeOverlay, Material etc -->
        <item name="popupTheme">@style/ThemeOverlay.AppCompat.Light</item>
       <!-- Tried android:textColor -->
       <!-- Tried android:textColorPrimary -->
    </style>
```

No idea what to do :/

![screen shot 2018-04-24 at 20 42 32](https://user-images.githubusercontent.com/49692/39187481-0b5c9350-4800-11e8-91cf-60a7c08ef3a7.png)
I want this inverted! :)

**Comment by fedeerbes** [comment]
Hi man, i just start working with this package, and searching for a solution that i found, i ended here.

Try this and let me know.

In this [URL](https://zendesk.jfrog.io/zendesk/simple/libs-releases-local/com/zopim/android/sdk/%5BRELEASE%5D/sdk-%5BRELEASE%5D-samples.zip) you will find a zopimChat sample, in ChatSample/src/res/values you will find all needed to full customize the chat.

All you need to do y paste this five .xml files inside the react-native-zendesk-chat module. Like this
![image](https://user-images.githubusercontent.com/18606335/42940378-a30caaec-8b2f-11e8-9918-055d54a9d423.png)

you can add or change colors in the colors.xml file.

**Comment by fbartho** [comment]
Hiya, I know this request was from years ago, so you probably/hopefully got past this issue before now. This is Native Level configuration, so I would reach out to https://developer.zendesk.com if you’re still struggling. And of course, please feel free to write back with your results!

We are updating this package this month, if you have any fixes you want to contribute back, please let us know.

Next release milestone: https://github.com/taskrabbit/react-native-zendesk-chat/milestone/1

I’m going to close this ticket, but if it’s still an issue, please let me know!
