### ISSUE TITLE
linker command failed with exit code 1

### ISSUE THREAD

**Issue by romreed** [taskrabbit/react-native-zendesk-chat#27]
i try install to ios 
i got this issue https://github.com/taskrabbit/react-native-zendesk-chat/issues/21
and make this staps:
Libraries/RNZendeskChat.xcodeproj > Build Settings > Framework Search Paths
Add: "${SRCROOT}/../../../ios/Pods/ZDCChat" (recursive)

a got this error 
![image](https://user-images.githubusercontent.com/16118227/39471157-40320dea-4d4a-11e8-9df8-56552c9ac063.png)

**Comment by dev-twoweb** [comment]
Same problem here. Any solution?

**Comment by fbartho** [comment]
That screenshot shows that your project is configured to deploy to iOS 8.0, but the framework `react-native-zendesk-chat` only supports >= iOS 9.2. If you change your App's DEPLOYMENT_TARGET to be a more modern iOS version, this probably will work.

**Comment by dev-twoweb** [comment]
In my case it is not the version. Displays the following error: 
ld: symbol (s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by fbartho** [comment]
That sounds like you're missing a step/framework/library.
@dev-twoweb -- Have you followed these instructions: https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/setup in addition to the instructions in this repo?

**Comment by dev-twoweb** [comment]
Yes, even following all documentation instructions the error persists. Follow the print with the complete error:
![Captura de Tela 2019-03-18 às 15 11 17](https://user-images.githubusercontent.com/43548289/54553204-71826500-4990-11e9-8ae3-fff7fdfcd4c3.png)

**Comment by fbartho** [comment]
@dev-twoweb What version of React-Native are you using? -- That looks like you just upgraded React-Native & you aren't linking to JavaScriptCore.framework

**Comment by dev-twoweb** [comment]
In my case this misses the problem. Thank you!

**Comment by fbartho** [comment]
Hiya, I know this request was from years ago, so you probably/hopefully got past this issue before now. But if anyone follows, please open a ticket with details so we can help!

We are updating this package this month, if you have any fixes you want to contribute back, please let us know.

Next release milestone: https://github.com/taskrabbit/react-native-zendesk-chat/milestone/1

I’m going to close this ticket, but if it’s still an issue, please let me know!
