### ISSUE TITLE
Could not find com.zopim.android:sdk:1.3.0.1 after doing all steps

### ISSUE THREAD

**Issue by hkjain1991** [taskrabbit/react-native-zendesk-chat#28]
Could not find com.zopim.android:sdk:1.3.0.1

please try to resolve

**Comment by fedeerbes** [comment]
Hi @hkjain1991 you solved this issue?

**Comment by beaapascual** [comment]
add this to your build.gradle

 maven { url 'https://zendesk.jfrog.io/zendesk/repo' }

**Comment by ShaBax** [comment]
added maven { url 'https://zendesk.jfrog.io/zendesk/repo' } but still 
same problem

**Comment by ShaBax** [comment]
@hkjain1991  any luck ?

**Comment by ShaBax** [comment]
@fedeerbes  you solved?

**Comment by fedeerbes** [comment]
Hi @ShaBax, yes i solved a few month ago. I don't remember exacty the changes that i made. But [here](https://github.com/VamosLacOrg/vamos-react-app/tree/master/android) you have the android part of a RN app that i used to work in, it has zendesk working there. 

i hope it helps you. Saludos.

**Comment by ShaBax** [comment]
i was adding ` maven { url 'https://zendesk.artifactoryonline.com/zendesk/repo' } ` in react-native-zendesk-chat module which is wrong . Just add in ` maven { url 'https://zendesk.artifactoryonline.com/zendesk/repo' } `   main gradle.build then it will work .

`allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven { url 'https://zendesk.jfrog.io/zendesk/repo' }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        google()
    }
}`

**Comment by fbartho** [comment]
Hiya, I know this request was from years ago, so you probably/hopefully got past this issue before now. It looks like there are several solutions above!

We are updating this package this month, if you have any fixes you want to contribute back, please let us know.

Next release milestone: https://github.com/taskrabbit/react-native-zendesk-chat/milestone/1

I’m going to close this ticket, but if it’s still an issue, please let me know!
