### ISSUE TITLE
Terminating with uncaught exception of type NSException

### ISSUE THREAD

**Issue by blaisebarre** [taskrabbit/react-native-zendesk-chat#29]
Hello,

I was able to install this module in React Native and I manage to compile the iOS application but when I run Zendesk.startChat, the physical phone freeze, the simulator phone crash and Xcode gets me the following error:

libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

Does anyone have a solution to this problem?

Thanks,
Blaise

**Comment by fbartho** [comment]
Hiya, I know this request was from years ago, so you probably/hopefully got past this issue before now. But if anyone follows, please open a ticket with details so we can help!

We are updating this package this month, if you have any fixes you want to contribute back, please let us know.

Next release milestone: https://github.com/taskrabbit/react-native-zendesk-chat/milestone/1

I’m going to close this ticket, but if it’s still an issue, please let me know!
