### ISSUE TITLE
Touch events are passing to background views instead of Chat Dialog/Modal

### ISSUE THREAD

**Issue by Dineshchitta** [taskrabbit/react-native-zendesk-chat#31]
When opening chat for the first time it is working fine. But When I end chat once and trying to open again it is opening but I could not type messages or click action buttons.I am opening it in modal so the second time when I was clicking send button / any other things the views which are in background of Modal are being clicked

**Comment by Dineshchitta** [comment]
@bleonard  Can you help us ? 

TIA

**Comment by fbartho** [comment]
Hiya, I know this request was from years ago, so you probably/hopefully got past this issue before now. That feels like a native problem with the Native android zendesk sdk, so you may want to reach out to https://developer.zendesk.com

If anyone follows, please open a ticket with details so we can help!

We are updating this package this month, if you have any fixes you want to contribute back, please let us know.

Next release milestone: https://github.com/taskrabbit/react-native-zendesk-chat/milestone/1

I’m going to close this ticket, but if it’s still an issue, please let me know!
