### ISSUE TITLE
How to open chat in a separate screen instead of modal in iOS

### ISSUE THREAD

**Issue by Dineshchitta** [taskrabbit/react-native-zendesk-chat#32]
I am new to iOS . I want to know how to open chat in a separate screen. 

TIA

**Comment by Dineshchitta** [comment]
@bleonard

**Comment by Dineshchitta** [comment]
@bleonard Can you help us ?

TIA

**Comment by fbartho** [comment]
I don’t understand the question, what do you mean by “separate screen”?

**Comment by fbartho** [comment]
Closing for now, feel free to ask again if you still need help.
