### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by pietro909** [taskrabbit/react-native-zendesk-chat#33]
Hi there,
please @bleonard are you still maintaining the project?

We need to understand whether the effort of collaborating via new PRs is worth it, thanks!

**Comment by davidtito1992** [comment]
Hi there!
I share this package that I did a few days ago react-native-zendesk-ichat, it lacks the pushNotifications (in a future version I will add it), but it is functional and has the latest versions of the SDK, it is also adapted for the latest versions of RN.

**Comment by bleonard** [comment]
We are not currently using it, unfortunately - so we haven't needed to upgrade and it's harder to verify fixes. Is there someone that would like to take it over?

**Comment by fbartho** [comment]
We are updating this package this month, if you have any fixes you want to contribute back, please let us know.

Next release milestone: https://github.com/taskrabbit/react-native-zendesk-chat/milestone/1
