### ISSUE TITLE
Execution failed for task ':app:mergeDebugResources'.

### ISSUE THREAD

**Issue by sudhirmurthy** [taskrabbit/react-native-zendesk-chat#34]
Execution failed for task ':app:mergeDebugResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
  /Users/sudhirmurthy/.gradle/caches/transforms-1/files-1.1/sdk-1.3.0.1.aar/128f52f50bb30f6f326d9f255f9d3d8d/res/layout/zopim_offline_message_fragment.xml:24: error: id 'id/..' has an invalid entry name.
  /Users/sudhirmurthy/.gradle/caches/transforms-1/files-1.1/sdk-1.3.0.1.aar/128f52f50bb30f6f326d9f255f9d3d8d/res/layout/zopim_offline_message_fragment.xml:39: error: id 'id/..' has an invalid entry name.

I'm using RN version 0.57.8 and android studio 3.3, gradle version 4.10.1
There seems to be a problem with react-native-zendesk-chat. Can you please help ?

**Comment by yanuwar** [comment]
try this
`implementation (project(':react-native-zendesk-chat')){
        exclude group: 'com.android.support'
        exclude module: 'appcompat-v7'
        exclude module: 'support-v4'
    }
    implementation "com.android.support:recyclerview-v7:${rootProject.ext.supportLibVersion}"`

**Comment by MattyK14** [comment]
Also seeing this with RN 0.59.2

**Comment by fbartho** [comment]
Hiya, I know this request was from years ago, so you probably/hopefully got past this issue before now. It looks like there was a working solution posted above. And if anyone follows, please open a ticket with details so we can help!

We are updating this package this month, if you have any fixes you want to contribute back, please let us know.

Next release milestone: https://github.com/taskrabbit/react-native-zendesk-chat/milestone/1

I’m going to close this ticket, but if it’s still an issue, please let me know!
