### ISSUE TITLE
\@synapsestudios\react-native-zendesk-support\android\build\intermediates\res\merged\release\drawable-xxxhdpi-v4\abc_text_select_handle_right_mtrl_light.png: error: file not found.

### ISSUE THREAD

**Issue by codal-mpawar** [taskrabbit/react-native-zendesk-chat#35]
the path is on npm modules

when i release the apk or run this command ./gradlew assembleRelease 

this error is generate and stop the process
help me any about that type error

**Comment by fbartho** [comment]
Hiya, I know this request was from a year ago, so you probably/hopefully got past this issue before now. But if anyone follows, please open a ticket with details so we can help!

We are updating this package this month, if you have any fixes you want to contribute back, please let us know.

Next release milestone: https://github.com/taskrabbit/react-native-zendesk-chat/milestone/1

I’m going to close this ticket, but if it’s still an issue, please let me know!
