### ISSUE TITLE
Cannot get the ChatWidget to work on Android

### ISSUE THREAD

**Issue by Shashank2406** [taskrabbit/react-native-zendesk-chat#39]
For some reason the chatwidget doesn't show up on android, but seems to work fine on iOS. Is there some extra steps required for widget to show up? 
react-native: 0.59.9

**Comment by romreed** [comment]
same issue on  "react-native": "0.61.5"

**Comment by fbartho** [comment]
Hiya, I know this request was from months ago, so you probably/hopefully got past this issue before now. We aren’t exhibiting this issue on react-native 0.59.10, so you may want to reach out to https://developer.zendesk.com

If anyone follows with the same question, please open a ticket with details so we can help!

We are updating this package this month, if you have any fixes you want to contribute back, please let us know.

Next release milestone: https://github.com/taskrabbit/react-native-zendesk-chat/milestone/1

I’m going to close this ticket, but if it’s still an issue, please let me know!

**Comment by sumeetm60** [comment]
> Hiya, I know this request was from months ago, so you probably/hopefully got past this issue before now. We aren’t exhibiting this issue on react-native 0.59.10, so you may want to reach out to https://developer.zendesk.com
> 
> If anyone follows with the same question, please open a ticket with details so we can help!
> 
> We are updating this package this month, if you have any fixes you want to contribute back, please let us know.
> 
> Next release milestone: https://github.com/taskrabbit/react-native-zendesk-chat/milestone/1
> 
> I’m going to close this ticket, but if it’s still an issue, please let me know!

Hi, Am facing the same issue, chatwidget doesn't show up on android, but works fine on iOS.  Am using react-native: "0.61.2". Can you please help me.
