### ISSUE TITLE
[QUESTION] Push notification

### ISSUE THREAD

**Issue by xchwarze** [taskrabbit/react-native-zendesk-chat#40]
How do I use Push notification?
I tried to do it but it seems that I am missing something
I already edit RNZendeskChatModule.java like this:
https://github.com/kundarmah/react-native-zendesk-chat/blob/master/android/src/main/java/com/taskrabbit/zendesk/RNZendeskChatModule.java

**Comment by fbartho** [comment]
Zendesk Manages that, and has a guide here: http://developer.zendesk.com/embeddables/docs/ios-chat-sdk/push_notifications

We don’t particularly integrate with that in our apps, but please feel free to contribute PRs if you find things we need to change!

We are updating this package this month, and our next release milestone: https://github.com/taskrabbit/react-native-zendesk-chat/milestone/1
