### ISSUE TITLE
build.gradle issue in version 3.0  (Android)

### ISSUE THREAD

**Issue by ShaBax** [taskrabbit/react-native-zendesk-chat#44]
The configuration is wrong for android 
node_modules/react-native-zendesk-chat/android/build.gradle
```
buildscript {
  repositories {
    jcenter()
  }

  dependencies {
    google()
    classpath 'com.android.tools.build:gradle:3.2.1'
  }
}
```
The solution is to move google() from dependencies to repositories
```
buildscript {
  repositories {
    jcenter()
  google()
  }

  dependencies {
    classpath 'com.android.tools.build:gradle:3.2.1'
  }
}
```

**Comment by enormousrodent** [comment]
Can you make this change for us please so if we need to refresh out node modules it won't break

**Comment by robertmurray** [comment]
@enormousrodent This change has been made.
