### ISSUE TITLE
Feature Request: Dark-Mode Options for Zendesk Chat

### ISSUE THREAD

**Issue by jeaniekarina** [taskrabbit/react-native-zendesk-chat#45]
The chat text is white and you can't read it when the iphone is in dark mode.

Does anyone know how to fix this ?

**Comment by jeaniekarina** [comment]
<img width="442" alt="Screen Shot 2020-02-06 at 3 17 20 PM" src="https://user-images.githubusercontent.com/8586586/73991381-d7594180-4900-11ea-8864-48cf4378bf53.png">

**Comment by jeaniekarina** [comment]
![Image from iOS (3)](https://user-images.githubusercontent.com/8586586/73991401-e809b780-4900-11ea-8804-8b4ea1aeca6c.png)

**Comment by fbartho** [comment]
@jeaniekarina -- unfortunately dark mode support needs to be discussed with Zendesk directly.

To my knowledge, we don't do any styling in react-native-zendesk-chat

(iOS code here: https://github.com/taskrabbit/react-native-zendesk-chat/blob/master/ios/RNZendeskChatModule.m )

**Comment by fbartho** [comment]
@jeaniekarina if you reach out to Zendesk and they do provide documentation for how to fix this, we'd be very appreciative for either that documentation or even better: a pull request implementing the changes needed. Please do let us know.

**Comment by fbartho** [comment]
@jeaniekarina I found this documentation for Zendesk iOS & Dark Mode: https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/customization#ios-13-and-dark-mode-support

**Comment by fbartho** [comment]
Closing as answered by Zendesk Documentation
