### ISSUE TITLE
Android install steps are missing a detail

### ISSUE THREAD

**Issue by gabrielmoncea** [taskrabbit/react-native-zendesk-chat#46]
Hello,
The README doesn't specify where exactly should I put the following line
`ZopimChat.init("YOUR_ZENDESK_ACCOUNT_KEY").build();`

I have some trouble building the project for Android.

I'm using ReactNative with ExpoKIT 0.35

**Comment by wadeyw** [comment]
Hi Team, Could you update your instruction for this?  since we do not import ZopimChat in MainActivity file, we should not initialize inside MainActivity as well.

**Comment by fbartho** [comment]
Unfortunately, we cannot give examples for everywhere that you might initialize your library. This package is not maintained or supported by Zendesk.

You choose what Java file to put that line of code in, based on your Application's needs.
For example, we decided to put it in a file called `EnvironmentManager.java` which is a native module we wrote for our application.

We do not provide user support for Expo either at this time. If you cannot write any Java code under Expo, either ask Expo to change, or you can contribute to this library to expose new APIs that would help you initialize Zendesk Chat from JavaScript.

**Comment by gabrielmoncea** [comment]
I'm closing this issue because I ditched zendesk in favour of intercom
