### ISSUE TITLE
Keyboard aware view on IOS

### ISSUE THREAD

**Issue by toastman** [taskrabbit/react-native-zendesk-chat#48]
Hello, 

i'm initializing chat like this 
```
ZendeskChat.startChat({})
```
on IOS keyboard overlap text box and user unable to see whole message

How we can fix this ? 

![Screen Shot 2020-03-11 at 5 09 04 PM_censored](https://user-images.githubusercontent.com/1378839/76432774-18d78380-63bc-11ea-9fca-05e82f4a348d.jpg)

![Screen Shot 2020-03-11 at 5 15 30 PM_censored](https://user-images.githubusercontent.com/1378839/76432751-12490c00-63bc-11ea-927e-c3a1615fd396.jpg)

**Comment by fbartho** [comment]
Hi @toastman!
A. This is a wrapper library, so we don't actually control the code that watches for the keyboard. That's Zendesk Chat iOS -- Docs here: https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/introduction
B. this is an open source project, and we don't work for Zendesk here. You may want to head over to that site to contact Zendesk directly!

You may also want to verify that you have the latest ios-chat-sdk using your Podfile or other techniques depending on how you installed the embedded library!

**Comment by toastman** [comment]
Here is a conversation about this issue 
https://develop.zendesk.com/hc/en-us/community/posts/360035890853-Zendesk-Chat-SDK-Keyboard-issues-on-iOS-13-x

**Comment by fbartho** [comment]
It looks like they say that this is fix with zendesk chat iOS 1.4.4 or later. If that works for you, should we close this ticket @toastman ?

**Comment by toastman** [comment]
I'm currently trying to solve this but without luck ( 
Will let you know when i solve this.

**Comment by fbartho** [comment]
I believe this will be fixed in #61 -- if you want to try it, please read that pull-request!
