### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by dex-labs** [taskrabbit/react-native-zendesk-chat#49]
Are there any screenshots of this in action? We are exploring possibilities for a client and just looking for an overview of what this module does,

Thanks

**Comment by fbartho** [comment]
This module wraps the underlying native SDKs from Zendesk (for their Chat Features). It serves to provide a platform agnostic react-native API.

Zendesk Docs: http://developer.zendesk.com/embeddables/docs/ios-chat-sdk/introduction

**Comment by dex-labs** [comment]
so it follows this video https://fast.wistia.net/embed/iframe/z07jgq4w96 ?

Am assuming its the part after the Live Chat is tapped and doesn't include the screen before that.
