### ISSUE TITLE
How can I get the reference of ZopimChat in main actiivty

### ISSUE THREAD

**Issue by mohanraj546** [taskrabbit/react-native-zendesk-chat#50]
In ios it is working fine but how can we get the reference of the ZopimChat in main activity

**Comment by fbartho** [comment]
It sounds like you’re asking about how to configure Android on the Java side of things? 

This would be the right place for those questions: http://developer.zendesk.com/embeddables/docs/android-chat-sdk/introduction

If I misunderstood, please let me know!

**Comment by mohanraj546** [comment]
I am asking about this issue

**Comment by wadeyw** [comment]
> In ios it is working fine but how can we get the reference of the ZopimChat in main activity

actually you do not need to initialize in MainActivity, you can directly do ZendeskChat.init() in your component and it's initialized globally

**Comment by enzzoperez** [comment]
Hi @wadeyw , is there any way to pass the ZENDESK_ACCOUNT_KEY to init method?

**Comment by wadeyw** [comment]
> Hi @wadeyw , is there any way to pass the ZENDESK_ACCOUNT_KEY to init method? .. Or how you say, do I have to put `ZendeskChat.init('ZENDESK_ACCOUNT_KEY')` in ComponentDidMount method of my Component?

yes, you need, but you can put in your first entry file, like index.js or App.js, only need to initialize once when you open the app, in other components you can directly use ZendeskChat to call other functions
