### ISSUE TITLE
Need to add dependencies for Android integration that might be redundant

### ISSUE THREAD

**Issue by TusharKoul** [taskrabbit/react-native-zendesk-chat#53]
While trying to build the package for Android I had to make the following additions - 

in `android/app/build.gradle`
```
dependencies {
    ...
    implementation group: "com.zopim.android", name: "sdk", version: '1.4.8'
    ...
}
```

in `android/build.gradle`
```
allprojects {
    repositories {
       ...
        maven { url 'https://zendesk.jfrog.io/zendesk/repo' }
    }
}
```

Without these changes I was getting errors while building for android - 
```
.../MainActivity.java:17: error: cannot find symbol
import com.zopim.android.sdk.api.ZopimChat;
                                ^
  symbol:   class ZopimChat
  location: package com.zopim.android.sdk.api
.../MainActivity.java:137: error: cannot find symbol
        ZopimChat.init(zendesk_key);
        ^
  symbol:   variable ZopimChat
  location: class MainActivity
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

FAILURE: Build failed with an exception.
```

These same changes seem to already be in this package's code.
See: https://github.com/taskrabbit/react-native-zendesk-chat/blob/master/android/build.gradle

Now I'm not too familiar with Android, but it seems like I should not be needed these changes since the dependencies are already defined with the package.

**Comment by fbartho** [comment]
@TusharKoul if you're on RN < 0.60 the `implementation` line should happen when you do `react-native link`

If you're on a later RN, then that should come from auto-linking. -- I'm not sure about the `maven` line.

Are you suggesting updating the Installation Instructions in the documentation or what are you proposing?

**Comment by TusharKoul** [comment]
@fbartho we're on RN 61.5 and we still needed the `implementation` line.

I had made some edits to the documentation but was unable to push my branch to remote, maybe I need to be added as a contributor?

Overall, I feel like if a project consumes `react-native-zendesk-chat`, it should work out of the box without additional changes to `build.gradle` since the required dependencies are already defined in this package and should get resolved automatically. 

But these are just my thoughts as a non-expert in android, maybe the way it is now is just how android packages are supposed to work 🤷‍♂️

**Comment by fbartho** [comment]
@robertmurray just did our upgrade to React-Native 0.62 so he's pretty in touch here. I think @robertmurray may know how to update our documentation to be clearer.

**Comment by fbartho** [comment]
@TusharKoul we don't have the `implementation` line anymore. We do have `implementation group:` for the zendesk side of things, but I don't know if that's required. Want to chat about this?

**Comment by TusharKoul** [comment]
@fbartho sure! could u pls point me towards the PR that makes the changes that you're talking about?

**Comment by fbartho** [comment]
@TusharKoul -- please look at #61 !
