### ISSUE TITLE
How to enable notification

### ISSUE THREAD

**Issue by wadeyw** [taskrabbit/react-native-zendesk-chat#54]
How push the token to zendesk so that I can receive the chat notification?

https://support.zendesk.com/hc/en-us/articles/360022365313-Enabling-push-notifications-for-the-Chat-SDK-for-mobile

**Comment by fbartho** [comment]
Hiya @wadeyw -- if you read the documentation at the URL you shared
> https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/push_notifications
> https://developer.zendesk.com/embeddables/docs/android-chat-sdk/push_notifications

You can set the push token from iOS Native using:
- `[ZDCChat setPushToken:tokenData];` (Objective-C - iOS)
- `ZopimChat.setPushToken(token);` (Java - Android)

This library isn't maintained by Zendesk, so if you *want* to do this from JS, we need to add that feature, and we need to add documentation explaining it all.
