### ISSUE TITLE
IOS Intergration

### ISSUE THREAD

**Issue by wadeyw** [taskrabbit/react-native-zendesk-chat#55]
I'm facing this issue while trying to pod install, any idea what's that means require a higher minimum deployment target

[!] CocoaPods could not find compatible versions for pod "RNZendeskChat":
  In Podfile:
    RNZendeskChat (from `../node_modules/react-native-zendesk-chat`)

Specs satisfying the `RNZendeskChat (from `../node_modules/react-native-zendesk-chat`)` dependency were found, but they required a higher minimum deployment target.

**Comment by fbartho** [comment]
If you're on RN 0.60 or later, then RNZendeskChat does not need to be included in your Podfile because of Autolinking.

We need to update the documentation, but haven't gotten there yet.

**Comment by fbartho** [comment]
https://reactnative.dev/docs/linking-libraries-ios#automatic-linking

**Comment by wadeyw** [comment]
> https://reactnative.dev/docs/linking-libraries-ios#automatic-linking

Thanks @fbartho, below my corrent version, I already run auto linked (Run react-native link react-native-zendesk-chat) and auto generated (pod 'RNZendeskChat', :path => '../node_modules/react-native-zendesk-chat') in my Podfile, but still have the same error, any idea which config have issue?

"react": "16.9.0",
 "react-native": "0.61.4",

**Comment by danilomartinelli** [comment]
Same error here :(... Any solution?

**Comment by wilo087** [comment]
Any solution for this?

**Comment by wadeyw** [comment]
> Any solution for this?

We endup give up this package, the UI is not able to integrate well with out platform, so we decide to directly use the Zendesk Support API

**Comment by henokweldemicael** [comment]
@wilo087 @danilomartinelli Had similar error but it worked after I upgraded `platform :ios, '10.0'` to 10 from 9 in Podfile

**Comment by wilo087** [comment]
> @wilo087 @danilomartinelli Had similar error but it worked after I upgraded `platform :ios, '10.0'` to 10 from 9 in Podfile

What React-Native version are you using? 

I already changed from 9 to 10, then I executed pod install to update the Pod Project and I still having the same issue.

**Comment by fbartho** [comment]
Please check if #61 is working for you, as I'm going to be merging that one soon!

**Comment by thuynt99** [comment]
I use RN 0.61 and i get same issue
