### ISSUE TITLE
Android - ZendeskChat.startChat function with `department` key  is not working as per functionality 

### ISSUE THREAD

**Issue by Gauravbtl** [taskrabbit/react-native-zendesk-chat#56]
Issue:- For android while initiating the chat with below constructor notice that department value is not passed to API properly.

> `ZendeskChat.startChat({`
>       `name: {firstName} ${lastName},`
>     `  email,`
>      ` phone: mobileNumber,`
>      ` department: Some Value`
>   `  })`

As per functionality, it should navigate to correct Department in case if the department is not under a working hour or no agent is available it should show the same message as in iOS.

**Comment by fbartho** [comment]
Yes, this is a missing feature @Gauravbtl 

I have now documented this in the TypeScript types definition file here: https://github.com/taskrabbit/react-native-zendesk-chat/blob/master/RNZendeskChat.d.ts#L10-L21

Please let me know if you want to contribute this enhancement.

**Comment by Gauravbtl** [comment]
> Yes, this is a missing feature @Gauravbtl
> 
> I have now documented this in the TypeScript types definition file here: https://github.com/taskrabbit/react-native-zendesk-chat/blob/master/RNZendeskChat.d.ts#L10-L21
> 
> Please let me know if you want to contribute this enhancement.

Yes, I can contribute to this.

**Comment by fbartho** [comment]
I’m not sure, but I believe this will come for free as I upgrade us to Zendesk Chat SDK v2

**Comment by Gauravbtl** [comment]
> I’m not sure, but I believe this will come for free as I upgrade us to Zendesk Chat SDK v2

Yes Zendesk Chat SDK v2 is free I already discussed to Zendesk support regarding this only the point is they are not giving any support to React native as of now.

**Comment by fbartho** [comment]
Fix for this is in #61 -- if you want to try it, please read that pull-request!
