### ISSUE TITLE
Update to ZendeskChatSDK v2 ?

### ISSUE THREAD

**Issue by jeaniekarina** [taskrabbit/react-native-zendesk-chat#57]
https://developer.zendesk.com/embeddables/docs/chat-sdk-v-2-for-ios/integration#adding-the-sdk-with-cocoapods

Are there any plans to update this v2? I don't know enough swift to do this myself. If it happens to be straight forward but you don't have any time to do it please point me to the right direction.

**Comment by Gauravbtl** [comment]
Any update on this?

**Comment by fbartho** [comment]
@Gauravbtl, @jeaniekarina -- I haven't yet investigated doing this. Hopefully somebody motivated will be able to open a PR about it!

If you don't mind my asking -- is there a particular rush? -- What extra value does the V2 provide? -- This will help prioritize things if we have to do this in house.

If anybody comes along with a good PR for this, I'm happy to help review it.

**Comment by fbartho** [comment]
I'm not sure, but this might be part of what we need: https://github.com/taskrabbit/react-native-zendesk-chat/compare/master...guustmc:master

@guustmc -- are you interested in contributing here?

**Comment by guustmc** [comment]
Hi @fbartho 
That fork is indeed what you need, it supports the V2 variant.  I've updated it for some work I needed to do for a client. It has a few client specific thingy's in it, but feel free to use that code to do the update

**Comment by fbartho** [comment]
This is implemented in #61 -- if you want to try it, please read that pull-request!

**Comment by fbartho** [comment]
Shipped in: https://github.com/taskrabbit/react-native-zendesk-chat/releases/tag/v0.4.0
