### ISSUE TITLE
ITMS-90809: Deprecated API Usage UIWebView

### ISSUE THREAD

**Issue by sushant3003** [taskrabbit/react-native-zendesk-chat#59]
When submitting app to app store we are getting following deprecation warning from apple. 
Issue Description:
**ITMS-90809**: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
As per apple documentation [](https://developer.apple.com/news/?id=12232019b) they said that app publishing is prohibited from 1st April 2020 and They will also stop updates to existing application having UIWebview from December 2020.
Traces of UIWebview are found in ZDCChat framework. 
 As release notes from zendesk they said that they resolved the error in v2 for zendesk chat sdk. 

Please let us know the plan for (react-native-zendesk-chat) when you are going to migrate to v2.

**Comment by Gauravbtl** [comment]
Any update on this?

**Comment by sushant3003** [comment]
> Any update on this?
Hi @Gauravbtl I found alternative library for the same . check this
https://www.npmjs.com/package/react-native-zendesk-chat-tmc

**Comment by fbartho** [comment]
I'm going to reopen this issue as we still need to update for this! Please let me know if that's a concern @sushant3003

**Comment by fbartho** [comment]
Looks like this is roughly what we'd need to do: https://github.com/taskrabbit/react-native-zendesk-chat/compare/master...guustmc:master

**Comment by samuelasd** [comment]
> 
> 
> When submitting app to app store we are getting following deprecation warning from apple.
> Issue Description:
> **ITMS-90809**: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
> As per apple documentation they said that app publishing is prohibited from 1st April 2020 and They will also stop updates to existing application having UIWebview from December 2020.
> Traces of UIWebview are found in ZDCChat framework.
> As release notes from zendesk they said that they resolved the error in v2 for zendesk chat sdk.
> 
> Please let us know the plan for (react-native-zendesk-chat) when you are going to migrate to v2.

Right know is worst than a warning, apple rejected my app because if this :/

**Comment by Gauravbtl** [comment]
Any update on this?

**Comment by fbartho** [comment]
I might get to take a look at this this week. Unsure!

**Comment by fbartho** [comment]
Fix for this is in #61 -- if you want to try it, please read that pull-request!

**Comment by fbartho** [comment]
Shipped in: https://github.com/taskrabbit/react-native-zendesk-chat/releases/tag/v0.4.0
