### ISSUE TITLE
Android app crashes on start chat function call

### ISSUE THREAD

**Issue by TayyabaAslamSeecs** [taskrabbit/react-native-zendesk-chat#60]
following is code i have written in componentDidMount function of my RN component.

```
ZendeskChat.init('MY_KEY').build();
    let chat = {
      name: 'name',
      email: 'email',
      phone: '234124234',
    };
ZendeskChat.startChat(chat);
```
It works perfectly fine for iOS.

I run `react-native link react-native-zendesk-chat` to link libraries.

**Comment by fbartho** [comment]
@TayyabaAslamSeecs -- I know the documentation was probably a little confusing.

I've updated the docs a bit:
![image](https://user-images.githubusercontent.com/209712/85637918-5db8ba80-b639-11ea-8eb4-adb84d17da91.png)

Is this line in java?

```
ZendeskChat.init('my_key').build()
```
- If it's in Java, then it should be `ZopimChat.init('MY_KEY').build()`
- If it's in JS, then you shouldn't call `.build()`

Is this set of lines in JavaScript?
```
    let chat = {
      name: 'name',
      email: 'email',
      phone: '234124234',
    };
ZendeskChat.startChat(chat);
```
(It should be in JS).
