### ISSUE TITLE
Latest RN version issue

### ISSUE THREAD

**Issue by yuvraj88** [taskrabbit/react-native-zendesk-chat#64]
My dependencies are
"dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/native": "^5.6.1",
    "@react-navigation/stack": "^5.6.2",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-reanimated": "^1.9.0",
    "react-native-safe-area-context": "^3.0.7",
    "react-native-screens": "^2.9.0",
    "react-native-zendesk-chat": "^0.4.0"
  },

while initializing by
ZendeskChat.init('My Key');

getting error

ould not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.zendesk:chat:2.2.0.
     Searched in the following locations:
       - file:/Users/shauryapratap/.m2/repository/com/zendesk/chat/2.2.0/chat-2.2.0.pom
       - file:/Users/shauryapratap/Documents/happ/MyTestApp/node_modules/react-native/android/com/zendesk/chat/2.2.0/chat-2.2.0.pom
       - file:/Users/shauryapratap/Documents/happ/MyTestApp/node_modules/jsc-android/dist/com/zendesk/chat/2.2.0/chat-2.2.0.pom
       - https://dl.google.com/dl/android/maven2/com/zendesk/chat/2.2.0/chat-2.2.0.pom
       - https://jcenter.bintray.com/com/zendesk/chat/2.2.0/chat-2.2.0.pom
       - https://www.jitpack.io/com/zendesk/chat/2.2.0/chat-2.2.0.pom
     Required by:
         project :app > project :react-native-zendesk-chat
   > Could not find com.zendesk:messaging:4.3.1.
     Searched in the following locations:
       - file:/Users/shauryapratap/.m2/repository/com/zendesk/messaging/4.3.1/messaging-4.3.1.pom
       - file:/Users/shauryapratap/Documents/happ/MyTestApp/node_modules/react-native/android/com/zendesk/messaging/4.3.1/messaging-4.3.1.pom
       - file:/Users/shauryapratap/Documents/happ/MyTestApp/node_modules/jsc-android/dist/com/zendesk/messaging/4.3.1/messaging-4.3.1.pom
       - https://dl.google.com/dl/android/maven2/com/zendesk/messaging/4.3.1/messaging-4.3.1.pom
       - https://jcenter.bintray.com/com/zendesk/messaging/4.3.1/messaging-4.3.1.pom
       - https://www.jitpack.io/com/zendesk/messaging/4.3.1/messaging-4.3.1.pom
     Required by:
         project :app > project :react-native-zendesk-chat

**Comment by jakmak24** [comment]
@yuvraj88 I think you might be missing
```
maven{
    url 'https://zendesk.jfrog.io/zendesk/repo'
}
```
in your build.gradle

**Comment by fbartho** [comment]
@yuvraj88 -- please check if @jakmak24's advice works for you!
