### ISSUE TITLE
Could not resolve all files for configuration ':app:debugCompileClasspath'.

### ISSUE THREAD

**Issue by damienteo** [taskrabbit/react-native-zendesk-chat#66]
Hi, I have installed `"react-native-zendesk-chat": "^0.4.0"`

I am on `"react-native": "0.59.2"`, and have been trying to set it up on my mobile app via `react-native run-android`, but I am receiving the following error when I am trying to do so.
`
* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find com.zendesk:chat:2.2.0.
  Required by:
      project :app
      project :app > project :react-native-zendesk-chat
> Could not find com.zendesk:messaging:4.3.1.
  Required by:
      project :app
      project :app > project :react-native-zendesk-chat
`

Setup-wise, I followed the instructions in the readme for https://github.com/taskrabbit/react-native-zendesk-chat
W.r.t. https://github.com/taskrabbit/react-native-zendesk-chat#ios-manually-setting-up-with-cocoapods, I did not experience any setup errors.

w.r.t https://github.com/taskrabbit/react-native-zendesk-chat#android-manual-setup--configuration, I have tried `react-native-link`, but I got the same error above when trying `react-native run-android`.
As such, I followed the steps to do a complete manual install (for when RN < 0.60). After following the steps (except for step 4), I still encountered the same error.

Is there anything else I should try?

**Comment by fbartho** [comment]
I would investigate Zendesk’s Documentation on getting Chat v2 setup on Android (outside of react-native). This sounds to me like a terribly confusing error message, but that probably means something is mismatched with your library or SDK versions.

Fallback option: downgrade to this library’s version 0.3.x until you’ve upgraded RN.

RN 0.60 came out a year ago, and the current version of RN is 0.63 (I’m on 0.62 myself), I highly recommend upgrading before you get more compatibility issues!

**Comment by damienteo** [comment]
Thank you for the reply!
Upgrading the version of RN is on our todo list. Will check again once done.

**Comment by buraksakalli** [comment]
I'm getting same error. How to solve this problem? I'm using react-native: `0.62.2`

**Comment by tinni95** [comment]
> I'm getting same error. How to solve this problem? I'm using react-native: `0.62.2`
> 
> Update:
> 
> I fixed the error with add `maven { url 'https://zendesk.jfrog.io/zendesk/repo' }` to `android/build.gradle`

I think this should be documented, I had to do the same to make it work

**Comment by FeMaffezzolli** [comment]
> I'm getting same error. How to solve this problem? I'm using react-native: `0.62.2`
> 
> Update:
> 
> I fixed the error with add `maven { url 'https://zendesk.jfrog.io/zendesk/repo' }` to `android/build.gradle`

I had the same problem and this step above made it work. I agree this could be documented.
