### ISSUE TITLE
No camera or photos permissions on IOS

### ISSUE THREAD

**Issue by literalltd** [taskrabbit/react-native-zendesk-chat#7]
Hi there

I am trying to use this and whilst the chat bit works really well, whenever I try to send a photo or access one from my camera roll I only get a black screen, it sends a black image to zendesk successfully though. Checking permissions shows that I am denied access to both the camera and the camera roll. I never get the permissions request popup when using this.

**Comment by fbartho** [comment]
Hiya, I know this request was from years ago, so you probably/hopefully got past this issue before now. But if anyone follows, Zendesk has docs about permissions here: https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/chat#attachments-and-camera-usage-on-ios-10

We are updating this package this month, if you have any fixes you want to contribute back, please let us know.

Next release milestone: https://github.com/taskrabbit/react-native-zendesk-chat/milestone/1

I’m going to close this ticket, but if it’s still an issue, please let me know!
