### ISSUE TITLE
ZDCChat/ZDCChat.h' file not found RN 0.63.2

### ISSUE THREAD

**Issue by geovannyPaiz** [taskrabbit/react-native-zendesk-chat#73]
When I try to initialize my project in iOS, my build failed
`
#import <ZDCChat/ZDCChat.h>
	[ZDCChat initializeWithAccountKey:@"key"];`

my app is in react-native 0.63.2

**Comment by fbartho** [comment]
@geovannyPaiz -- what version of react-native-zendesk-chat are you using? What versions are in your Cocoapods?

**Comment by geovannyPaiz** [comment]
i v

> @geovannyPaiz -- what version of react-native-zendesk-chat are you using? What versions are in your Cocoapods?

I have te 0.4.0 version

**Comment by fbartho** [comment]
`ZDCChat/ZDCChat.sh` don't need to be imported into your AppDelegate in the new version of `react-native-zendesk-chat`.

You can initialize the library straight from JS. -- Documentation here: https://github.com/taskrabbit/react-native-zendesk-chat#quickstart--usage

--- 

If you need to do Advanced native things, the full documentation is here: https://developer.zendesk.com/embeddables/docs/chat-sdk-v-2-for-ios/getting_started (for iOS -- this and Android links are in the top of the Readme!)

```objective-c
#import <ChatSDK/ChatSDK.h>
#import <ChatProvidersSDK/ChatProvidersSDK.h>

// ...
[ZDKChat initializeWithAccountKey:<#"Your account key"#> appId:<#Your app identifier#> queue:dispatch_get_main_queue()];
```

**Comment by geovannyPaiz** [comment]
> `ZDCChat/ZDCChat.sh` don't need to be imported into your AppDelegate in the new version of `react-native-zendesk-chat`.
> 
> You can initialize the library straight from JS. -- Documentation here: https://github.com/taskrabbit/react-native-zendesk-chat#quickstart--usage
> 
> If you need to do Advanced native things, the full documentation is here: https://developer.zendesk.com/embeddables/docs/chat-sdk-v-2-for-ios/getting_started (for iOS -- this and Android links are in the top of the Readme!)
> 
> ```objc
> #import <ChatSDK/ChatSDK.h>
> #import <ChatProvidersSDK/ChatProvidersSDK.h>
> 
> // ...
> [ZDKChat initializeWithAccountKey:<#"Your account key"#> appId:<#Your app identifier#> queue:dispatch_get_main_queue()];
> ```

thanks but now i have this problem, the message no send
![image](https://user-images.githubusercontent.com/18633731/93828300-3a95ab00-fc28-11ea-8931-5454418b571c.png)

**Comment by geovannyPaiz** [comment]
Works perfectly
