### ISSUE TITLE
iOS ignores name and tags options

### ISSUE THREAD

**Issue by chentselee** [taskrabbit/react-native-zendesk-chat#76]
Our app runs into issues similar to #65 but with iOS instead. Works fine on Android.

- react-native-zendesk-chat: v0.4.0
- iOS version: 13.7

Thanks!

**Comment by SeanArmstrong** [comment]
Hi @chentselee, its probably worth including some of your setup to help the maintainers. 

Ive been fighting similar issues an I think the issues are with the iOS SDK. For some examples see here - https://develop.zendesk.com/hc/en-us/community/posts/360044000874-iOS-SDK-v2-visitor-info-not-included-in-chat

Here is a snippet from one comment in that thread
>There are 2 scenarios we see with the SDK V2.

> 1. Disabling pre-chat form allows us to set the user's department, but visitorInfo is not included. This scenario is going on with the snippet provided by Marcel.

> 2. Enabling pre-chat form includes visitorInfo but, we have to stop setting user's department otherwise the chat screen freezes and nothing is sent to the agents.

____________________________________________

My issue which was similar to v2 (although kinda the opposite) where setting `showPreChatForm: false` the Zendesk UI would fail to work/connect if department is set. Luckily i can do without for now

**Comment by fbartho** [comment]
@chentselee -- @SeanArmstrong's advice is correct!

We're using tags & presetting the name (and allowing users to fill one in) and I checked in our Zendesk and even added new tags :) as recently as a month ago.

So… I think tags / name do work at least with some versions of zendesk-chat-ios (the underlying library). -- I would direct this question to Zendesk Customer Support!

**Comment by fbartho** [comment]
I'm going to close this issue for now, but if it's still occurring, we can reopen!
