### ISSUE TITLE
Can't create ipa file iOS

### ISSUE THREAD

**Issue by fajarazay** [taskrabbit/react-native-zendesk-chat#80]
Succesfully running on iOS & build archive, but when I wanna create ipa file there is error like this. Why? 

![Screen Shot 2020-10-09 at 09 31 40](https://user-images.githubusercontent.com/14243792/95548310-f7607800-0a2e-11eb-9ce9-24f7a367bdd2.png)

**Comment by fbartho** [comment]
Were you able to resolve this @fajarazay -- this doesn't really seem like an issue with the Library per-se. / this is the first time I've seen this!

**Comment by fbartho** [comment]
Additionally, the error message is about ChatProvidersSDK.framework which is owned by Zendesk -- so I would reach out to their customer support!

**Comment by fajarazay** [comment]
Solved after update Catalina & Xcode to the latest version.
