### ISSUE TITLE
Keyboard aware view on Android (react-native-zendesk-chat 0.4.0, Zendesk Android SDK v2)

### ISSUE THREAD

**Issue by tukhai** [taskrabbit/react-native-zendesk-chat#94]
Hi,

Android keyboard overlap text box and user is unable to see whole text box when user is typing.

How can we fix this ?

<img width="345" alt="Screenshot 2020-12-10 at 4 52 20 PM" src="https://user-images.githubusercontent.com/22212239/101749274-81e55680-3b08-11eb-9055-e8405bc23d31.png">

After user select the input text box, the keyboard goes up & cover the input text box => user  is unable to see whole text box when user is typing.
<img width="346" alt="Screenshot 2020-12-10 at 4 52 32 PM" src="https://user-images.githubusercontent.com/22212239/101749393-a6d9c980-3b08-11eb-803a-e94d2162e698.png">

**Comment by ArtemVass** [comment]
I've got the same issue with 0.4.0 and 0.4.1

**Comment by fbartho** [comment]
@tukhai and @ArtemVass I believe this is an upstream issue -- you can try using different versions of Zendesk's Native SDK. That said, your navigation bar is also rendering behind cutouts from the hardware, so that generally suggests your app might be configured weirdly? -- There are standard AndroidManifest.xml flags you can use to customize this behavior (particularly around the keyboard)

**Comment by ArtemVass** [comment]
@fbartho Yes, that was an issue with the app itself. Thanks!

**Comment by tukhai** [comment]
@ArtemVass and @fbartho , can you share a bit about which AndroidManifest.xml file did you make change on?
I've tried it for a while, but couldn't fix it

**Comment by mullarkb** [comment]
Not looking to reopen this, just looking to be pointed in the right direction if possible. I've implemented this library into an ejected expo app. The display is almost identical to the screenshots above. 

I have tried adding: ` <activity android:name="com.zendesk.chat" android:windowSoftInputMode="adjustResize" />` and ` <activity android:name="com.zendesk.messaging.MessagingActivity" android:windowSoftInputMode="adjustResize" />` to `AndroidManifest.xml` 
      
@ArtemVass, @tukhai or @fbartho could you share what you added to AndroidManifest.xml to solve this? 

Any help would be appreciated :)

**Comment by sdillon1224** [comment]
Having same issue (Keyboard hiding the text field) with our Android version on Bare, ejected, React Native integration.  Any resolution or point in the right direction, whether that be through AndroidManifest.xml or otherwise would be greatly appreciated.

**Comment by hozhaojung** [comment]
Hi @tukhai , you can add this into AndroidManifest.xml
```<activity android:name="zendesk.messaging.MessagingActivity" android:theme="@style/ZendeskTheme" />```

Then, create the chat_style.xml  in `android/app/src/main/res/values/chat_style.xml` and put 

```xml
<?xml version="1.0" encoding="utf-8"?>
  <resources>
  <!-- Base chat sdk theme. -->
  <style name="ZendeskTheme"  parent="Theme.MaterialComponents.Light">
    <!-- Customize chat theme here. -->
    <item name="colorAccent">@color/colorAccent</item>
    <item name="colorPrimary">@color/colorPrimary</item>
    <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
    <item name="android:fitsSystemWindows">true</item>
  </style>
</resources>
```


```<item name="android:fitsSystemWindows">true</item> ``` is the key.
Hope this help your issue. :)
