### ISSUE TITLE
The chat interface can't follow the iphone system language

### ISSUE THREAD

**Issue by zhudax** [taskrabbit/react-native-zendesk-chat#99]
<img width="290" alt="截屏2021-01-13 12 35 16" src="https://user-images.githubusercontent.com/33782306/104447417-0f9ae280-559c-11eb-9702-55c3899831af.png">
<img width="287" alt="截屏2021-01-13 12 36 06" src="https://user-images.githubusercontent.com/33782306/104447443-19244a80-559c-11eb-81b2-cbc07a7e7d44.png">
Hi, I want change the language. But the chat interface can't follow the iphone system language. How could I change the language ?

**Comment by zhudax** [comment]
I find how to change language:
https://medium.com/swift-productions/localizing-your-ios-app-xcode-12-swift-5-3-74559a431e79

**Comment by Davi9130** [comment]
> I find how to change language: https://medium.com/swift-productions/localizing-your-ios-app-xcode-12-swift-5-3-74559a431e79

This work if you want to overwrite the phrase, if you want to change the language auto (using the device language) follow the steps above :
<img width="522" alt="Screenshot 2022-03-16 at 15 53 26" src="https://user-images.githubusercontent.com/41929096/158665672-95754469-f0f2-46c2-be87-83e3201588fa.png">
<img width="511" alt="Screenshot 2022-03-16 at 15 53 33" src="https://user-images.githubusercontent.com/41929096/158665696-5fabafa4-255c-4c4a-9ce3-177a8cf8ee62.png">
